name: "[CI] JavaScript"
on:
  push:
    branches:
      - develop
      - release/*
      - "*-stable"
  pull_request:
    branches-ignore:
      - "chore/l10n*"
    paths:
      - "*"
      - ".github/**"
      - "decidim-admin/**"
      - "decidim-comments/**"
      - "decidim-core/**"
      - "decidim-dev/**"

env:
  CI: "true"
  NODE_VERSION: 22.14.0
  NODE_ENV: "test"
  SHAKAPACKER_RUNTIME_COMPILE: "false"

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: Tests
    runs-on: ubuntu-22.04
    if: "!startsWith(github.head_ref, 'chore/l10n')"
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 1
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Get npm cache directory path
        id: npm-cache-dir-path
        run: echo "dir=$(npm get cache)-javascript" >> $GITHUB_OUTPUT
      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir-path.outputs.dir }}
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-
      - name: Install JS dependencies
        run: npm ci
      - run: npm run test
        name: Test JS files

