name: "[CI] Production compile check"
on:
  push:
    branches:
      - develop
      - release/*
      - "*-stable"
  pull_request:
    branches-ignore:
      - "chore/l10n*"

env:
  CI: "false"
  SIMPLECOV: "false"
  RUBY_VERSION: 3.4.7
  NODE_VERSION: 22.14.0
  NODE_ENV: "production"
  RAILS_ENV: production
  BUNDLE_WITHOUT: "development:test"
  SHAKAPACKER_RUNTIME_COMPILE: "false"

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: Tests
    runs-on: ubuntu-22.04
    if: "!startsWith(github.head_ref, 'chore/l10n')"
    timeout-minutes: 60
    services:
      postgres:
        image: postgres:14@sha256:d508bf6220b5c7b7cd9c735d6abd5ea2e6e4e45882a29ed704f625aba32bd935
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
    env:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: localhost
      DECIDIM_SPAM_DETECTION_BACKEND_RESOURCE: "memory"
      DECIDIM_SPAM_DETECTION_BACKEND_USER: "memory"
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 1
      - run: |
          sudo apt-get update && sudo apt-get install libvips libvips-tools
        name: Install libvips
        shell: "bash"
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Get npm cache directory path
        id: npm-cache-dir-path
        run: echo "dir=$(npm get cache)-${{ env.DECIDIM_MODULE }}" >> $GITHUB_OUTPUT
      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir-path.outputs.dir }}
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-
      - run: bundle exec decidim-generators/exe/decidim test-application
        name: Create app
